---
- name: Configure network devices from SoT
  # hosts defined on AAP
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: Check topology type
      ansible.builtin.set_fact:
        topology_type: "{{ group_names[1].split('_')[0] }}"

    - name: Set config paths for SoT in case of dev topology
      ansible.builtin.set_fact:
        config_template: "{{ infra_path }}/{{ inventory_hostname | replace('dev', 'prod') }}/templates/{{ inventory_hostname | replace('dev', 'prod') }}.j2"
        config_vars: "{{ infra_path }}/{{ inventory_hostname | replace('dev', 'prod') }}/config_vars"
      when: topology_type == 'dev'

    - name: Include SoT configuration variables
      ansible.builtin.include_vars:
        dir: "{{ config_vars }}"

    - name: Adjust SoT in case of dev topology
      ansible.builtin.include_vars:
        file: "{{ infra_path }}/dev/{{ inventory_hostname }}"
      when: topology_type == 'dev'



  roles:
    - apply_configuration_from_sot



