---
- name: Configure network devices
  hosts: a01-dev-rtr1
  gather_facts: false
  vars:
    config_path: "{{ infra_path }}/{{ inventory_hostname }}/templates/{{ inventory_hostname }}.j2"

  tasks:
    - debug:
        var: config_path

    - name: Apply configuration from SoT
      arista.eos.eos_config:
        src: "{{ config_path }}"
        replace: config
        save_when: modified
      #   backup: "{{ eos_config_deploy_eapi_pre_running_config_backup }}"
      #   backup_options:
      #     filename: "{{ pre_running_config_backup_filename }}"
      #     dir_path: "{{ pre_running_config_backup_dir }}"
      # notify: "backup config"