---

- name: Configure network devices
  hosts: dev_arista01
  gather_facts: false

  tasks:
    - name: Include configuration variables for {{ inventory_hostname }}
      ansible.builtin.include_vars:
        dir: "{{ config_vars }}"

    - name: Backup running config before changes
      arista.eos.eos_config:
        backup: true
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/pre_changes

    - name: Apply configuration from SoT
      arista.eos.eos_config:
        src: "{{ config_template }}"
        replace: config
        save_when: modified
      register: config_output
      notify:
        - backup post_changes
        - copy backup
        - show configuration changes

    - name: Inform if no configuration changes introduced
      ansible.builtin.debug:
        msg: "No configuration changes introduced"
      when: not config_output.changed

  handlers:
    - name: Backup running config after changes
      arista.eos.eos_config:
        backup: true
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/post_changes
      listen: backup post_changes

    - name: Copy backups from EE to {{ inventory_hostname }}
      ansible.builtin.copy:
        src: /tmp/backups/
        dest: /tmp/backups
        mode: preserve
      listen: copy backup

    - name: Show configuration changes
      ansible.builtin.debug:
        msg: "{{ config_output.diff | to_json(indent=2) }}"
      listen: show configuration changes
