---

- name: Configure network devices
  hosts: a01-dev-rtr1
  gather_facts: false

  tasks:
    - name: Include configuration variables for {{ inventory_hostname }}
      ansible.builtin.include_vars:
        dir: "{{ config_vars }}"

    - name: Apply configuration from SoT
      arista.eos.eos_config:
        src: "{{ config_template }}"
        replace: config
        save_when: modified
        backup: true
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/pre_changes
      notify: "backup post_changes"

  handlers:
    - name: Backup running config
      arista.eos.eos_config:
        backup: true
        backup_options:
          dir_path: /tmp/backups/{{ inventory_hostname }}/post_changes
      listen: "backup post_changes"


- name: Copy backups
  hosts: labhost
  gather_facts: false

  tasks:
    - name: Copy backups from EE to {{ inventory_hostname }}
      ansible.builtin.copy:
        src: /tmp/backups/
        dest: /tmp/backups
        mode: preserve
