---
- name: Configure dev network devices
  hosts: clab-ceos_dev-ceos1
  gather_facts: false
  vars:
    # config_path: "{{ infra.dev.path }}/{{ infra.dev.topology }}/{{ infra.dev.topology.config_file }}"
    config_path: "{{ infra.dev.path }}/{{ infra.dev.topology[0] }}"
  vars_files:
    - vars.yml

  tasks:
    - debug:
        var: config_path

    # - name: Replace configuration with intended configuration
    #   arista.eos.eos_config:
    #     src: "{{ config_path }}.cfg"
      #   replace: config
      #   save_when: modified
      #   backup: "{{ eos_config_deploy_eapi_pre_running_config_backup }}"
      #   backup_options:
      #     filename: "{{ pre_running_config_backup_filename }}"
      #     dir_path: "{{ pre_running_config_backup_dir }}"
      # notify: "backup config"
      # tags: [provision]