---
- name: Create dev infrastructure
  hosts: labhost
  gather_facts: false
  vars_files:
    - lab_vars.yml

  tasks:
    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ labhost.remote_repo_path }}"
        dest: "{{ labhost.local_repo_path }}"
        update: true

    - name: Deploy dev topology
      ansible.builtin.command:
        cmd: clab deploy --reconfigure -t "{{ labhost.local_repo_lab_path }}/{{ labhost.lab_name }}/{{ labhost.topology_file }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ labhost.clab_labdir }}"
      register: clab_deploy_output
      changed_when: clab_deploy_output.rc != 0


    - name: Show dev infrastructure
      ansible.builtin.debug:
        msg: "{{ clab_deploy_output.stdout_lines }}"
