---
- name: Create testing environment
  hosts: localhost
  gather_facts: false
  vars_files:
    - lab_vars.yml

  tasks:
    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ labhost.remote_repo_path }}"
        dest: "{{ labhost.local_repo_path }}"
        update: true

    - name: Create dev infrastructure
      ansible.builtin.command:
        cmd: clab deploy --reconfigure -t "{{ labhost.local_repo_topology_path }}/{{ labhost.topology_file }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ labhost.clab_labdir }}"
      register: output
      changed_when: clab_deploy_output.rc != 0


    - name: Show dev infrastructure
      ansible.builtin.debug:
        msg: "{{ clab_deploy_output.stdout_lines }}"
