---
- name: Create network infrastructure
  hosts: labhost
  gather_facts: false
  vars:
    mode: "deploy" # Default action to deploy network topology, use 'destroy' to destroy topology
  vars_files:
    - vars.yml

  tasks:
    - name: Check mode parameter
      ansible.builtin.fail:
        msg: "Mode must be deploy or destroy"
      when: mode not in ["deploy", "destroy"]

    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ git.repo_url }}"
        dest: "{{ git.dest_path }}"
        update: true

    - name: Conditionally deploy or destroy network infrastructure
      ansible.builtin.command:
        cmd: "{{ lookup('template', 'clab_command.j2') }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ clab.labdir }}"
      register: clab_output
      changed_when: clab_output.stderr | regex_search('(Adding|Removing) containerlab')


    - name: Show network infrastructure
      ansible.builtin.debug:
        msg: "{{ clab_output.stdout_lines }}"
