---
- name: Manage network infrastructure with clab
  hosts: labhost
  gather_facts: false
  vars:
    mode: "deploy" # Default action to deploy network topology, use 'destroy' to destroy topology
    topology_path: "/tmp/netdevops/dev_infra/arista01/dev_arista01.clab.yml"
    labdir: /tmp/clab

  tasks:
    - name: Validate mode parameter
      ansible.builtin.assert:
        that: mode in ["deploy", "destroy"]
        fail_msg: "Mode must be deploy or destroy"

    - name: Deploy network infrastructure
      ansible.builtin.command:
        cmd: clab deploy --reconfigure -t "{{ topology_path }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ labdir }}"
      register: clab_output
      changed_when: "'Adding containerlab' in clab_output.stderr"
      when: mode == 'deploy'

    - name: Remove network infrastructure
      ansible.builtin.command:
        cmd: clab destroy -t "{{ topology_path }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ labdir }}"
      register: clab_output
      changed_when: "'Removing containerlab' in clab_output.stderr"
      when: mode == 'destroy'

    - name: Collect network infrastructure
      ansible.builtin.command:
        cmd: clab inspect --all
      become: true
      register: clab_inspect
      changed_when: clab_inspect.rc != 0

    - name: Show network infrastructure
      ansible.builtin.debug:
        var: clab_inspect.stdout_lines
