---
- name: Create network infrastructure
  hosts: labhost
  gather_facts: false
  vars:
    mode: "deploy" # Default action to deploy network topology, use 'destroy' to destroy topology
  vars_files:
    - vars.yml

  tasks:
    - name: Check mode parameter
      ansible.builtin.fail:
        msg: "Mode must be deploy or destroy"
      when: mode not in ["deploy", "destroy"]

    - name: Clone git repository
      ansible.builtin.git:
        repo: "{{ git.repo_url }}"
        dest: "{{ git.dest_path }}"
        update: true

    - name: Survey
      ansible.builtin.set_fact:
        survey: infra.dev.topology_file
        
    - name: Deploy network infrastructure
      ansible.builtin.command:
        cmd: clab deploy --reconfigure -t "{{ infra.dev.path }}/{{ infra.dev.topology }}/{{ survey }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ clab.labdir }}"
      register: clab_output
      changed_when: "'Adding containerlab' in clab_output.stderr"
      when: mode == 'deploy'

    - name: Remove network infrastructure
      ansible.builtin.command:
        cmd: clab destroy -t "{{ infra.dev.path }}/{{ infra.dev.topology }}/{{ survey }}"
      become: true
      environment:
        CLAB_LABDIR_BASE: "{{ clab.labdir }}"
      register: clab_output
      changed_when: "'Removing containerlab' in clab_output.stderr"
      when: mode == 'destroy'

    - name: Collect network infrastructure
      ansible.builtin.command:
        cmd: clab inspect --all
      become: true
      # environment:
      #   CLAB_LABDIR_BASE: "{{ clab.labdir }}"
      register: clab_inspect

    - name: Show network infrastructure
      ansible.builtin.debug:
        var: clab_inspect.stdout_lines
