---
- name: Manage network infrastructure with clab
  hosts: labhost
  gather_facts: false
  vars:
    # Default action to deploy network topology, use 'destroy' to destroy topology
    mode: deploy
    # Default topology file, provide your topology file when running playbook via -e parameter or Survey
    topology_file: topologies/arista01/dev_arista01.clab.yml

  roles:
    - create_infrastructure
