---
- name: Test Arista infrastructure
  hosts: prod_arista01
  gather_facts: false

  pre_tasks:
    - name: Include SoT configuration variables
      ansible.builtin.include_vars:
        dir: "{{ config_vars }}"

  roles:
    - network_testing_arista


- name: Test clients connectivity
  hosts: labhost
  gather_facts: false

  roles:
    - role: network_testing_clients
      vars:
        a01_client1_container: clab-prod_arista01-a01-prod-client1
        a01_client2_container: clab-prod_arista01-a01-prod-client2