---
- name: Test Arista infrastructure
  hosts: dev_arista01
  gather_facts: false

  pre_tasks:
    - name: Set config paths for SoT for dev topology
      ansible.builtin.set_fact:
        config_template: "{{ infra_path }}/{{ inventory_hostname | replace('dev', 'prod') }}/templates/{{ inventory_hostname | replace('dev', 'prod') }}.j2"
        config_vars: "{{ infra_path }}/{{ inventory_hostname | replace('dev', 'prod') }}/config_vars"

    - name: Include SoT configuration variables
      ansible.builtin.include_vars:
        dir: "{{ config_vars }}"

    - name: Adjust SoT for dev topology
      ansible.builtin.include_vars:
        file: "{{ infra_path }}/dev/{{ inventory_hostname }}"

  roles:
    - network_testing_arista



- name: Test clients connectivity
  hosts: labhost
  gather_facts: false

  roles:
    - role: network_testing_clients
      vars:
        a01_client1_container: clab-dev_arista01-a01-dev-client1
        a01_client2_container: clab-dev_arista01-a01-dev-client2