# For pre-check use --skip-tags postchecks
---
- name: Test Arista infrastructure in prod
  hosts: prod_arista01
  gather_facts: false

  roles:
    - role: set_sot_variables
    - role: network_testing_arista
      vars:
        route: 172.16.0.1/32

- name: Test clients connectivity
  hosts: labhost
  gather_facts: false

  roles:
    - role: network_testing_clients
      vars:
        a01_client1_container: clab-prod_arista01-a01-prod-client1
        a01_client2_container: clab-prod_arista01-a01-prod-client2
