---
- name: Backup running config before changes
  arista.eos.eos_config:
    backup: true
    backup_options:
      dir_path: /tmp/backups/{{ inventory_hostname }}/pre_changes

- name: Apply configuration from SoT
  arista.eos.eos_config:
    src: "{{ config_template }}"
    replace: config
    save_when: modified
  register: config_output
  notify:
    - backup post_changes
    - copy backup
    - show configuration changes

- name: Inform if no configuration changes introduced
  ansible.builtin.debug:
    msg: "No configuration changes introduced"
  when: not config_output.changed
