---
- name: Validate mode parameter
  ansible.builtin.assert:
    that: mode in ["deploy", "destroy"]
    fail_msg: "Mode must be deploy or destroy"

- name: Copy topology file to {{ inventory_hostname }}
  ansible.builtin.copy:
    src: "../{{ topology_file }}"
    dest: /tmp/{{ topology_file }}/
    mode: preserve

- name: Deploy network infrastructure on {{ inventory_hostname }}
  ansible.builtin.command:
    cmd: clab deploy --reconfigure -t /tmp/{{ topology_file }}
  become: true
  environment:
    CLAB_LABDIR_BASE: "{{ labdir }}"
  register: clab_output
  changed_when: "'Adding containerlab' in clab_output.stderr"
  when: mode == 'deploy'

- name: Remove network infrastructure from {{ inventory_hostname }}
  ansible.builtin.command:
    cmd: clab destroy -t /tmp/{{ topology_file }}
  become: true
  environment:
    CLAB_LABDIR_BASE: "{{ labdir }}"
  register: clab_output
  changed_when: "'Removing containerlab' in clab_output.stderr"
  when: mode == 'destroy'

- name: Collect invormation about network infrastructures on {{ inventory_hostname }}
  ansible.builtin.command:
    cmd: clab inspect --all
  become: true
  register: clab_inspect
  changed_when: clab_inspect.rc != 0

- name: Show network infrastructures on {{ inventory_hostname }}
  ansible.builtin.debug:
    var: clab_inspect.stdout_lines
