---    
- name: Backup running config after changes
  arista.eos.eos_config:
    backup: true
    backup_options:
      dir_path: /tmp/backups/{{ inventory_hostname }}/post_changes
  listen: backup post_changes

- name: Copy backups from EE to {{ inventory_hostname }}
  ansible.builtin.copy:
    src: /tmp/backups/
    dest: /tmp/backups
    mode: preserve
  listen: copy backup

- name: Show configuration changes
  ansible.builtin.debug:
    msg: "{{ config_output.diff }}"
  listen: show configuration changes
