---
- name: Ping client node
  ansible.builtin.command:
    cmd: docker exec {{ a01_client1_container }} ping -c 5 {{ a01_client2_ip }}
  register: ping_result
  ignore_errors: true
  changed_when: false
  become: true

- name: Ping output
  ansible.builtin.debug:
    msg: "{{ ping_result.stdout.split('\n')  }}"

- name: Extract packet loss
  ansible.builtin.set_fact:
    packet_loss: "{{ ping_result | regex_search('(\\d+)% packet loss') | regex_search('(\\d+\\.?\\d*)') }}"

- name: Verify ping results
  ansible.builtin.assert:
    that:
      - "{{ packet_loss | float }} == 0"
    fail_msg: "Ping failed"
    success_msg: "Ping successful"
