name: prod_arista01

mgmt:
  network: prod
  ipv4-subnet: 172.100.20.0/24

topology:
  nodes:
    a01-prod-rtr1:
      kind: arista_ceos
      image: ceos:4.32.0F 
      mgmt-ipv4: 172.100.20.2


    a01-prod-rtr2:
      kind: arista_ceos
      image: ceos:4.32.0F
      mgmt-ipv4: 172.100.20.3

    a01-prod-client1:
      kind: linux
      image: wbitt/network-multitool:fedora
      mgmt-ipv4: 172.100.20.4
      exec:
        - ip addr add 192.168.1.2/24 dev eth1
        - ip route add 192.168.2.0/24 via 192.168.1.1

    a01-prod-client2:
      kind: linux
      image: wbitt/network-multitool:fedora
      mgmt-ipv4: 172.100.20.5
      exec:
        - ip addr add 192.168.2.2/24 dev eth1
        - ip route add 192.168.1.0/24 via 192.168.2.1

  links:
    - endpoints: ["a01-prod-rtr1:eth1", "a01-prod-rtr2:eth1"]
    - endpoints: ["a01-prod-rtr1:eth2", "a01-prod-client1:eth1"]
    - endpoints: ["a01-prod-rtr2:eth2", "a01-prod-client2:eth1"]
