name: CD

on:
  pull_request_target: 
    types: [closed]  
  workflow_dispatch:

jobs:
  Launch_deployment_workflow:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment to prod hook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        verify_ssl: false
