name: CI

on:
  push:
    branches:
      - 'cfg_update**'
  workflow_dispatch:

jobs:
  Launch_developement_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke testing in dev hook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL_CI }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET_CI }}
        verify_ssl: false
